### ISSUE TITLE
Does not count with interrupt

### ISSUE THREAD

**Issue by kuzmanzs** [SensorsIot/Geiger-Counter-RadiationD-v1.1-CAJOE-#5]
I am using wemos mini and it does not counts from the detector.

I have checked via simple wire if I put to gnd it was counted.

Detector board looks like fine, It makes counting noise and blinking led. But via P3 VIN does not sense anyting. Should I do some modification on the detector board??

**Comment by mgwoj** [comment]
@kuzmanzs have you resolved this issue?

**Comment by kuzmanzs** [comment]
Yes, it has caused the build in pull up resistor for I2C

**Comment by 123LY321** [comment]
hi

Sorry to disturb you, I want to use STM32 instead of MCU in this circuit diagram. Do I need to change any hardware? After I design according to the circuit diagram, STM32 can't enter interruption and read data, which is similar to your question. Is it convenient to say where you were originally?

I look forward to your reply. Thank you.
